In the Simple Linear Regression model we would simply use the following equations for the estimation:
$$
Y_i=\beta_{0}+\beta_{1} X_{i} + e_{i}
$$
$$
{\displaystyle {\begin{gather*}
{\widehat {\beta_{1} }}={\frac {\sum _{i=1}^{n}{(x_{i}-{\bar {x}})(y_{i}-{\bar {y}})}}
{\sum _{i=1}^{n}{(x_{i}-{\bar {x}})^{2}}}}\\
{\widehat {\beta_{0} }}={\bar {y}}-{\widehat {\beta_{1} }}\,{\bar {x}}\ \end{gather*}}}
$$

The equation would be enough for analyizing the data that has one regressor and one target variable. But in real life cases we often have more than one regressor as this study focuses, the multi-linear model. So what will be done to expand the model as a multi-lienar model. Firstly we need to define our model's sample formula:
$$
Y_{i}=\beta_{0}+\beta_{1} X_{i1}+\beta_{2} X_{i2}+\cdots+\beta_{p} X_{in}+e_{i}
$$

Becaues there ara many independent variables we will rout to the matrix approach for MLR. So for that we need to define these matrices: 
$$\displaystyle  {X} ={\begin{bmatrix}1 & X_{11} & X_{12} & \cdots & X_{1p} \\ 
1 & X_{21} & X_{22} & \cdots & X_ {2p} \\
 \vdots &\vdots &\ddots &\vdots \\ 1 & X_{n1}&X_{n2}&\cdots &X_{np}\end{bmatrix}},
\qquad { {\beta }}={\begin{bmatrix}\beta _{0}\\\beta _{1}\\\vdots \\\beta _{p}\end{bmatrix}},\qquad  {y} ={\begin{bmatrix}y_{1}\\y_{2}\\\vdots \\y_{n}\end{bmatrix}},\qquad  {e} ={\begin{bmatrix}e_{1}\\e_{2}\\\vdots \\e_{n}\end{bmatrix}}$$

We want to minimize the sum of the squared errors, $e$. In matrix notation, the OLS model is $y=Xb+e$, where $e=y-Xb$. The sum of the squared error is:
$$
\begin{equation}
\sum e^{2}_i = 
\begin{bmatrix}
  e_1 & e_2 & \cdots & e_n \\ 
\end{bmatrix}
\begin{bmatrix}
  e_1 \\
  e_2 \\
  \vdots \\
  e_n \\
\end{bmatrix}
=
e'e
\tag{11.1}
\end{equation}
$$

Therefore, we want to find the $\beta$ that minimizes this function:
$$
\begin{align*}
e'e &= (y-X\beta)'(y-X\beta) \\
&=y'y-\beta'X'y-y'X\beta+\beta'X'X\beta \\
&=y'y-2\beta'X'y+\beta'X'X\beta \\
\end{align*}
$$

To do this we take the derivative of $e'e$ w.r.t $\beta$ and set it equal to $0$. Through this proces we will continue with the equation and find $\beta$:
$$
\begin{equation*}
\frac{\partial e'e}{\partial \beta}=-2X'y+2X'X\beta=0   
\end{equation*}
$$
$$
\begin{equation*}
  -2X'X\beta=-2X'y
\end{equation*}
$$
$$
\begin{equation*}
(X'X)\beta=X'y
\end{equation*}
$$
$$
\begin{equation}
\beta = (X'X)^{-1}X'y  
\end{equation}
$$

So in the end we found out that the as the OLS states the coefficients($\beta$) that has the minimum errors are matrix equation $\beta = (X'X)^{-1}X'y $.

## Importing Libraries

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

## Importing The Data

In [2]:
df = pd.read_csv("startups.csv")
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

## Data Processing

In [3]:
# getting the dummies
df = pd.get_dummies(df, columns=['State'], drop_first=True, dtype=int)
df.head()

R&D Spend  Administration  Marketing Spend     Profit  State_Florida  \
0  165349.20       136897.80        471784.10  192261.83              0   
1  162597.70       151377.59        443898.53  191792.06              0   
2  153441.51       101145.55        407934.54  191050.39              1   
3  144372.41       118671.85        383199.62  182901.99              0   
4  142107.34        91391.77        366168.42  166187.94              1   

   State_New York  
0               1  
1               0  
2               0  
3               1  
4               0

In [4]:
# # if not want to use dummy method this is the option to use as classes
# classes = df['State'].unique().tolist()
# display(f"Label classes: {classes}")

# df['State'] = df['State'].map(classes.index)
# display(f"Labelled classes: {df['State'].unique().tolist()}")

## Matrix Preparations

In [ ]:
# for demonstrating we will use 10 samples
# creating the target and the independet varaibles
target = "Profit"
y = df[target][:10].values
X = df.iloc[:10, df.columns != 'Profit'].values
# first column must be 1's because of the intercept
row_num = X.shape[0]
ones = np.ones(row_num)
X = np.c_[ones, X]

display(X)
display(y)

array([[1.0000000e+00, 1.6534920e+05, 1.3689780e+05, 4.7178410e+05,
        0.0000000e+00, 1.0000000e+00],
       [1.0000000e+00, 1.6259770e+05, 1.5137759e+05, 4.4389853e+05,
        0.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 1.5344151e+05, 1.0114555e+05, 4.0793454e+05,
        1.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 1.4437241e+05, 1.1867185e+05, 3.8319962e+05,
        0.0000000e+00, 1.0000000e+00],
       [1.0000000e+00, 1.4210734e+05, 9.1391770e+04, 3.6616842e+05,
        1.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 1.3187690e+05, 9.9814710e+04, 3.6286136e+05,
        0.0000000e+00, 1.0000000e+00],
       [1.0000000e+00, 1.3461546e+05, 1.4719887e+05, 1.2771682e+05,
        0.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 1.3029813e+05, 1.4553006e+05, 3.2387668e+05,
        1.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 1.2054252e+05, 1.4871895e+05, 3.1161329e+05,
        0.0000000e+00, 1.0000000e+00],
       [1.0000000e+00, 1.2333488e+05,

array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94, 156991.12,
       156122.51, 155752.6 , 152211.77, 149759.96])

In [11]:
# X^T matrix
xt_mx = X.T
# X^T*y matrix
xty_mx = xt_mx @ y
xty_mx

display(xt_mx)
display(xty_mx)

array([[1.0000000e+00, 1.0000000e+00, 1.0000000e+00, 1.0000000e+00,
        1.0000000e+00, 1.0000000e+00, 1.0000000e+00, 1.0000000e+00,
        1.0000000e+00, 1.0000000e+00],
       [1.6534920e+05, 1.6259770e+05, 1.5344151e+05, 1.4437241e+05,
        1.4210734e+05, 1.3187690e+05, 1.3461546e+05, 1.3029813e+05,
        1.2054252e+05, 1.2333488e+05],
       [1.3689780e+05, 1.5137759e+05, 1.0114555e+05, 1.1867185e+05,
        9.1391770e+04, 9.9814710e+04, 1.4719887e+05, 1.4553006e+05,
        1.4871895e+05, 1.0867917e+05],
       [4.7178410e+05, 4.4389853e+05, 4.0793454e+05, 3.8319962e+05,
        3.6616842e+05, 3.6286136e+05, 1.2771682e+05, 3.2387668e+05,
        3.1161329e+05, 3.0498162e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 0.0000000e+00,
        1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 0.00

array([1.69503217e+06, 2.41145770e+11, 2.11800994e+11, 6.05174452e+11,
       5.12990930e+05, 6.84366710e+05])

In [12]:
# x^T*x matrix
xtx_mx = xt_mx @ X
display(xtx_mx)

array([[1.00000000e+01, 1.40853605e+06, 1.24942632e+06, 3.50403498e+06,
        3.00000000e+00, 4.00000000e+00],
       [1.40853605e+06, 2.00592989e+11, 1.76161580e+11, 5.02562506e+11,
        4.25846980e+05, 5.62141030e+05],
       [1.24942632e+06, 1.76161580e+11, 1.61060038e+11, 4.33623463e+11,
        3.38067380e+05, 5.04103310e+05],
       [3.50403498e+06, 5.02562506e+11, 4.33623463e+11, 1.30995068e+12,
        1.09797964e+06, 1.52945837e+06],
       [3.00000000e+00, 4.25846980e+05, 3.38067380e+05, 1.09797964e+06,
        3.00000000e+00, 0.00000000e+00],
       [4.00000000e+00, 5.62141030e+05, 5.04103310e+05, 1.52945837e+06,
        0.00000000e+00, 4.00000000e+00]])

In [13]:
def matrix_cofactor(matrix):
 
    try:
        determinant = np.linalg.det(matrix)
        if(determinant!=0):
            cofactor = None
            cofactor = np.linalg.inv(matrix).T * determinant
            # return cofactor matrix of the given matrix
            return cofactor
        else:
            raise Exception("singular matrix")
    except Exception as e:
        print("could not find cofactor matrix due to",e)

# cofactor matrix
# its just transpose of the inverse time determinant => (A^-1)^T * det(A) 
co_xtx_mx = matrix_cofactor(xtx_mx)
co_xtx_mx

array([[ 1.33952693e+32, -8.37054324e+26, -2.34404835e+26,
         6.28807594e+25, -1.17327289e+31, -1.08193602e+31],
       [-8.37054324e+26,  9.90197529e+21, -1.17103717e+21,
        -1.34175897e+21,  5.45167325e+25,  1.06099727e+26],
       [-2.34404835e+26, -1.17103717e+21,  2.45637947e+21,
         2.22813371e+20,  4.22769444e+25,  4.21364696e+24],
       [ 6.28807594e+25, -1.34175897e+21,  2.22813371e+20,
         3.24995222e+20, -1.64741142e+25, -2.66632222e+25],
       [-1.17327289e+31,  5.45167325e+25,  4.22769444e+25,
        -1.64741142e+25,  8.42436786e+30,  5.04233691e+30],
       [-1.08193602e+31,  1.06099727e+26,  4.21364696e+24,
        -2.66632222e+25,  5.04233691e+30,  7.94638063e+30]])

In [14]:
# adjoint matrix
# just the transpose of cofator matrix => cof(X)^T
adj_xtx_mx = co_xtx_mx.T
display(adj_xtx_mx)

det_xtx_mx = np.linalg.det(xtx_mx)
display(det_xtx_mx)

array([[ 1.33952693e+32, -8.37054324e+26, -2.34404835e+26,
         6.28807594e+25, -1.17327289e+31, -1.08193602e+31],
       [-8.37054324e+26,  9.90197529e+21, -1.17103717e+21,
        -1.34175897e+21,  5.45167325e+25,  1.06099727e+26],
       [-2.34404835e+26, -1.17103717e+21,  2.45637947e+21,
         2.22813371e+20,  4.22769444e+25,  4.21364696e+24],
       [ 6.28807594e+25, -1.34175897e+21,  2.22813371e+20,
         3.24995222e+20, -1.64741142e+25, -2.66632222e+25],
       [-1.17327289e+31,  5.45167325e+25,  4.22769444e+25,
        -1.64741142e+25,  8.42436786e+30,  5.04233691e+30],
       [-1.08193602e+31,  1.06099727e+26,  4.21364696e+24,
        -2.66632222e+25,  5.04233691e+30,  7.94638063e+30]])

9.494916648335748e+30

In [15]:
# inverse matrix => adj(A) / det(A)
inv_xtx_mx = adj_xtx_mx/det_xtx_mx
inv_xtx_mx

array([[ 1.41078324e+01, -8.81581540e-05, -2.46874031e-05,
         6.62257098e-06, -1.23568530e+00, -1.13948975e+00],
       [-8.81581540e-05,  1.04287122e-09, -1.23333065e-10,
        -1.41313402e-10,  5.74167574e-06,  1.11743716e-05],
       [-2.46874031e-05, -1.23333065e-10,  2.58704690e-10,
         2.34665958e-11,  4.45258721e-06,  4.43779247e-07],
       [ 6.62257098e-06, -1.41313402e-10,  2.34665958e-11,
         3.42283386e-11, -1.73504568e-06, -2.80815758e-06],
       [-1.23568530e+00,  5.74167574e-06,  4.45258721e-06,
        -1.73504568e-06,  8.87250323e-01,  5.31056469e-01],
       [-1.13948975e+00,  1.11743716e-05,  4.43779247e-07,
        -2.80815758e-06,  5.31056469e-01,  8.36908940e-01]])

In [16]:
# beta coefficients matrix
beta_mx = inv_xtx_mx @ xty_mx
beta_mx

array([ 1.95338082e+04,  1.00454568e+00, -4.05025793e-03,  2.08338383e-02,
        1.70029724e+03,  2.92809871e+03])

## Final Results

In [18]:
# just testing out if it is working or not
result = X @ beta_mx
display("Manual MLR", np.round(result, 2))
# sklearn library is the way to go but we did everything manually
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X, y)

pred = lr.predict(X)
display("Sckit-Learn MLR", np.round(pred, 2))

'Manual MLR'

array([197837.33, 191505.62, 183462.29, 174993.45, 171245.95, 162093.8 ,
       156825.83, 158282.69, 149442.13, 149343.09])

'Sckit-Learn MLR'

array([197837.33, 191505.62, 183462.29, 174993.45, 171245.95, 162093.8 ,
       156825.83, 158282.69, 149442.13, 149343.09])